# Generated by Django 6.1.1 on 2026-09-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calcado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço')),
                ('estoque', models.IntegerField(verbose_name='estoque')),
                ('tamanho', models.IntegerField(verbose_name='tamanho')),
            ],
            options={
                'verbose_name': 'calçado',
                'verbose_name_plural': 'calçados',
                'ordering': ['nome'],
            },
        ),
    ]
