# Generated by Django 6.1.1 on 2026-10-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calcado',
            old_name='tamanho',
            new_name='numeracao',
        ),
        migrations.AlterField(
            model_name='calcado',
            name='numeracao',
            field=models.CharField(max_length=20, verbose_name='numeração'),
        ),
    ]
